### ISSUE TITLE
Error while running. 

### ISSUE THREAD

**Issue by isukrit** [sugeerth/BrainModulyzer#12]
Hi, I get the following error while running the tool:

Files
Reading NII files.
Setting up the correlation table display.
Setting up main GUI.
Setting up Slice Views
Setting up the IsoSurfaces
Traceback (most recent call last):
  File "/home/sukrit/BrainModulyzer/src/brain-vis/BrainViewer.py", line 130, in <module>
    ParcelationPlot = ParcelationPlotWindow(parcelation_filename, template_filename, correlationTable,selectedColor,colorTable, slice_views[0],slice_views[1],slice_views[2])
  File "/home/sukrit/BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 123, in __init__
    self.setDataset()
  File "/home/sukrit/BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 225, in setDataset
    self.ParcelationReader = vtk.vtkNIFTIImageReader()
AttributeError: 'module' object has no attribute 'vtkNIFTIImageReader'

**Comment by sugeerth** [comment]
Yes, the issue is still pending for windows and linux. The installation in these machines should be done using http://www.vtk.org/Wiki/VTK/Configure_and_Build

**Comment by sugeerth** [comment]
Did you happen to install?
