### ISSUE TITLE
ImportError: No module named qt

### ISSUE THREAD

**Issue by isukrit** [sugeerth/BrainModulyzer#13]
Here is another error I get even before the other one:
Traceback (most recent call last):
  File "/home/sukrit/BrainModulyzer/src/brain-vis/BrainViewer.py", line 12, in <module>
    from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
  File "/usr/lib/python2.7/dist-packages/vtk/qt/QVTKRenderWindowInteractor.py", line 36, in <module>
    import qt
ImportError: No module named qt

**Comment by sugeerth** [comment]
Yes, the issue is still pending for windows and linux. The installation in these machines should be done using http://www.vtk.org/Wiki/VTK/Configure_and_Build

**Comment by sugeerth** [comment]
Just curious if you got it rectified?
